// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mdd_test_perm_c
Rcpp::List mdd_test_perm_c(const arma::mat& X, const arma::mat& Y, int R);
RcppExport SEXP _MDD_mdd_test_perm_c(SEXP XSEXP, SEXP YSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(mdd_test_perm_c(X, Y, R));
    return rcpp_result_gen;
END_RCPP
}
// mdd_test_boot_c
Rcpp::List mdd_test_boot_c(const arma::mat& X, const arma::mat& Y, int B);
RcppExport SEXP _MDD_mdd_test_boot_c(SEXP XSEXP, SEXP YSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(mdd_test_boot_c(X, Y, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MDD_mdd_test_perm_c", (DL_FUNC) &_MDD_mdd_test_perm_c, 3},
    {"_MDD_mdd_test_boot_c", (DL_FUNC) &_MDD_mdd_test_boot_c, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MDD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
