# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mdd_test_perm_c <- function(X, Y, R) {
    .Call('_MDD_mdd_test_perm_c', PACKAGE = 'MDD', X, Y, R)
}

mdd_test_boot_c <- function(X, Y, B) {
    .Call('_MDD_mdd_test_boot_c', PACKAGE = 'MDD', X, Y, B)
}

